name: The Bot Host

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
     - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: unzip
        run: |
         unzip -P ${{ secrets.ZIP_PASSWORD }} spam.zip
         cd x && unzip -P ${{ secrets.ZIP_PASSWORD }} xtelebot.zip
         rm -rf xtelebot.zip
      
      - name: Install dependencies
        run: rm -rf package-lock.json && npm i && pip install -r requirements.txt

      - name: Set TERM variable
        run: export TERM=xterm

      - name: Start The Spam
        run: node index.js &

      - name: Start The Code
        run: python x.py &
      
      - name: Keep Alive
        id: check_runs
        run: |
          echo "has_new_run=false" >> $GITHUB_OUTPUT
          while true; do
            sleep 1
            latest_run=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1&status=queued&status=in_progress" | \
              jq -r '.workflow_runs[0].id')
            if [[ $latest_run != ${{ github.run_id }} ]]; then
              echo "has_new_run=true" >> $GITHUB_OUTPUT
              break
            fi
          done

      
      - name: Stop application
        run: |
          pkill -f "node"
      
      - name: Delete Cache and Commit Logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "out session update" --allow-empty)

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      
      - name: Stop Workflow
        if: steps.check_runs.outputs.has_new_run == 'true'
        run: exit 0

      - name: Keep Alive
        if: steps.check_runs.outputs.has_new_run == 'false'
        run: sleep 60
